version: 2.8.1.{build}
os:
  - Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  # Force MSBuild 14
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - nuget restore
build:
  publish_wap: true
  verbosity: normal
test:
  categories:
    except:
    - AutomationTests
deploy:
  provider: WebDeploy
  skip_symbols: false
  server: https://dustedcodes.scm.azurewebsites.net:443/msdeploy.axd?site=dustedcodes
  website: dustedcodes
  username: $dustedcodes
  password:
    secure: h1vtujFnnnocUWjFBiKiIZ4LEpmTIcxcqgP8GlDxhJFYH2FKmsrvyMWY27K8ewCNhcFmenTeJYfTuuUzFX8Rbg==
  remove_files: true
  app_offline: true
  skip_dirs: '\\App_Data\\Logs;\\newrelic'
  on:
    branch: master
    appveyor_repo_tag: true